#:kivy 2.0.0

<ComplexPlane>:
    canvas.before:
        Color:
            rgba: 0, 0, 0, 1  # 黑色背景
        Rectangle:
            pos: self.pos
            size: self.size

<Label>:
    font_size: '14sp'
    color: 1, 1, 1, 1

<Button>:
    font_size: '14sp'
    background_color: 0.2, 0.2, 0.2, 1
    background_normal: ''
    color: 1, 1, 1, 1
    size_hint_y: None
    height: '48dp'
    padding: '10dp'